# Generated by Django 3.0 on 2019-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebot', '0011_auto_20191228_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contacts_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='share_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_message_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
